name: Test with GraalVM JDK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up GraalVM 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          cache: maven
      - name: Install dependencies
        run: |
          gu upgrade
          gu install python
          gu install R 
          gu install js
          gu install llvm
          gu install ruby
      - name: Compile C++
        run: |
          cd spring-openjdk/src/test/resources/scripts
          c++ hello.cpp -o hello -fPIC -pie -shared
          c++ hello_func.cpp -o hello_func -fPIC -pie -shared
      - name: Build with Maven
        run: cd spring-graaljdk && mvn -B package -e -X