name: Test with OpenJDK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile C++
        run: |
          cd spring-openjdk/src/test/resources/scripts
          c++ hello.cpp -o hello -fPIC -pie -shared
          c++ hello_func.cpp -o hello_func -fPIC -pie -shared
      - name: Build with Maven
        run: cd spring-openjdk && mvn -B package -e -X